function [ Y_out ] = axpy_unb( alpha, X, Y )

  [ XT, ...
    XB ] = FLA_Part_2x1( X, ...
                         0, 'FLA_TOP' );

  [ YT, ...
    YB ] = FLA_Part_2x1( Y, ...
                         0, 'FLA_TOP' );

  while ( size( XT, 1 ) < size( X, 1 ) )

    [ X0, ...
      x1t, ...
      X2 ] = FLA_Repart_2x1_to_3x1( XT, ...
                                    XB, ...
                                    1, 'FLA_BOTTOM' );

    [ Y0, ...
      y1t, ...
      Y2 ] = FLA_Repart_2x1_to_3x1( YT, ...
                                    YB, ...
                                    1, 'FLA_BOTTOM' );

    %------------------------------------------------------------%
    y1t = alpha * x1t + y1t
    %------------------------------------------------------------%

    [ XT, ...
      XB ] = FLA_Cont_with_3x1_to_2x1( X0, ...
                                       x1t, ...
                                       X2, ...
                                       'FLA_TOP' );

    [ YT, ...
      YB ] = FLA_Cont_with_3x1_to_2x1( Y0, ...
                                       y1t, ...
                                       Y2, ...
                                       'FLA_TOP' );

  end

  Y_out = [ YT
            YB ];

return